name: Docker Image CI

on: 
  push:
    branches: [master]
    pull_request: [master]
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nginx-rtmp:latest
        docker tag nginx-rtmp ifreecomm/nginx-rtmp:http-flv-custom
        docker login -u zyq0407 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ifreecomm/nginx-rtmp:http-flv-custom
