name: Docker Image CI

on: 
  push: 
    branches: [flv_http2]
  pull_request:
    branches: [flv_http2]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nginx-rtmp:latest
        docker tag nginx-rtmp zyq0407/nginx-rtmp:http2_flv
        docker login -u zyq0407 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push zyq0407/nginx-rtmp:http2_flv
