name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nginx-rtmp:latest
        docker tag nginx-rtmp ifreecomm/nginx-rtmp:secret-fcgi
        docker login -u kangliqi -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ifreecomm/nginx-rtmp:secret-fcgi
